services:
  employee-service:
    image: ilr-stock/employee-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
       aliases:
        - "employee-service"
networks:
  backend:
    driver: bridge